config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  devise_for :users, controllers:{
    confirmations: 'confirmations'
  }
  resources :users
  resources :courses
  root 'home#index'
  get 'landing_page/index'
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :user
    validates :title, :price, :level, :language, :short_description, presence: true
    validates :description, presence:true, length: {:minimum => 25}
    def to_s
        title
    end
    has_rich_text :description
    extend FriendlyId
    friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
  def to_s
   email 
  end
  has_many :courses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource)
      root_path
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if params[:title]
      @courses = Course.where('title ILIKE ?',"%#{params[:title]}%")
    else
      @courses = Course.all
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description,:short_description,:language,:level,:price)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index]
  def index
    @courses = Course.limit(4)
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(created_at: :desc)
    @q = User.ransack(params[:q])
    @users = @q.result(distinct:true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/confirmations_helper.rb
module ConfirmationsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.haml
%figure{:class => "attachment attachment--#{blob.representable? ? "preview" : "file"} attachment--#{blob.filename.extension}"}
  - if blob.representable?
    = image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ])
  %figcaption.attachment__caption
    - if caption = blob.try(:caption)
      = caption
    - else
      %span.attachment__name= blob.filename
      %span.attachment__size= number_to_human_size blob.byte_size

app/views/courses/_course.html.haml
.card.text-center.col-lg-3.my-2
  .card-header
    = link_to course.title, course_path(course)
  .card-body
    %p.card-text
    %small= simple_format(course.short_description)
  .card-footer.text
    .fas.fa-globe-asia
    = course.language
    .fas.fa-signal
    = course.level
    .fas.fa-money-check-alt
    = number_to_currency(course.price)
  .card-footer.text-muted
    .far.fa-user
    = course.user
    %br
    .far.fa-clock
    = course.created_at.strftime('%d-%b-%Y')
    
    %br
    = link_to 'Show', course, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
.container
  = simple_form_for(@course) do |f|
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

    .form-inputs
      = f.input :title
      = f.label :description
      = f.rich_text_area :description
      = f.input :short_description
      = f.input :language, collection: ["English", "Filipino", "Japanese"]
      = f.input :level, as: :select, collection: ["Beginner", "Intermediate", "Advanced"]
      = f.input :price

    .form-actions
      %p
      = f.button :submit, class: 'btn btn-success'

app/views/courses/edit.html.haml
.container 
  = link_to 'Show', @course
  \|
  = link_to 'Back', courses_path
  .card
    .card-header.text-center
      %h2 Edit Course
    .card-body
      = render 'form' 

app/views/courses/index.html.haml
%h1
  - if @courses.count == 0
    No Search Results
  - else
    Courses:
    = @courses.count

.d-flex.flex-wrap.container
  - @courses.each do |course|
    = render 'course', course:course


= link_to 'New Course', new_course_path

app/views/courses/new.html.haml
.container 
  .card
    .card-header.text-center
      %h2 New course
    .card-body
      = render 'form'

app/views/courses/show.html.haml
.container
  = link_to 'Course', courses_path(@course)
  \/
  = link_to @course.title, course_path(@course)
  %p
.card.text-center.w-75.mx-auto
  .card-header
    = @course.title
  .card-body
    %p.card-text
    = @course.description
  .card-footer
    .fas.fa-globe-asia
    = @course.language
    .fas.fa-signal
    = @course.level
    .fas.fa-money-check-alt
    = number_to_currency(@course.price)
  .card-footer.text-muted
    .far.fa-user
    = @course.user
    %br
    .far.fa-clock
    = @course.created_at.strftime('%d-%b-%Y') 
    %br
    = link_to 'Show', @course, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_course_path(@course), class: 'btn btn-sm btn-warning'
    = link_to 'Destroy', @course, method: :delete, data: { confirm: 'Are you sure?' },class: 'btn btn-sm btn-danger'

app/views/home/index.html.haml
.container.bg-transparent.text-light
  .bg-transparent.text-dark
    %h1.display-4 Start Learning!
    %hr
  = form_tag(courses_path, method: :get) do
    .input-group
      = text_field_tag :title, params[:title], autocomplete: 'on', placeholder: "Search", class: 'form-control-lg'
      %span.input-group-append.ms-1
        %button.btn.btn-primary.btn-lg{:type => "submit"}
          %span.fa.fa-search{"aria-hidden" => "true"}
    %hr

.card-group.container
  .card.card-body
    %h1
      .fa.fa-graduation-cap.text-success
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h1
      .fa.fa-brain.text-info
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h1
      .fa.fa-user-graduate.text-warning
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h1
      .fa.fa-infinity.text-danger
    Lifetime access
    .row
    Learn on your schedule
.container
  %hr
    %h2
      Popular Courses 
  .d-flex.flex-wrap.container.align-items-stretch 
    - @courses.each do |course|
      = render 'courses/course', course:course
  %hr
    %h2
      Top Rated Courses
  .d-flex.flex-wrap.container.align-items-stretch 
    - @courses.each do |course|
      = render 'courses/course', course:course
  %hr
    %h2
      Most Recent Courses 
  .d-flex.flex-wrap.container.align-items-stretch 
    - @courses.each do |course|
      = render 'courses/course', course:course

app/views/landing_page/index.html.haml
%h1 LandingPage#index
%p Find me in app/views/landing_page/index.html.erb

app/views/layouts/_navbar.html.haml
= stylesheet_link_tag "navbar", :media => "all" 

%nav.navbar.navbar-expand-lg.navbar-light.bg-info 
  = link_to root_path, class: 'nav-link' do
    .fas.fa-user-graduate
    Edukeyt
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-bs-target" => "#navbarSupportedContent", "data-bs-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.me-auto
        %li.nav-item{class: "#{'active fw-bolder' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active fw-bolder' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fas.fa-university
            Courses
        %li.nav-item{class: "#{'active fw-bolder' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            Add Course
        %li.nav-item{class: "#{'active fw-bolder' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
        %ul.navbar-nav.ms-auto
      .form-inline.my-2.my-lg-0
        = form_tag(courses_path, method: :get) do
          .input-group
            = text_field_tag :title, params[:title], autocomplete: 'on', placeholder: "Search", class: 'form-control-sm'
            %span.input-group-append
              %button.btn.btn-primary.btn-sm{:type => "submit"}
                %span.fa.fa-search{"aria-hidden" => "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Another link
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-bs-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/layouts/_notification.html.haml
-flash.each do |name,msg|
    -if msg.is_a?(String)
        %div{:class=> "alert alert-#{ name.to_s =='notice'? 'success': 'danger'}", :role => alert }
            %button.close{"aria-hidden" => "true", "data-bs-dismiss" => "alert", :type => "button"} &times
            = content_tag :span, msg, :id =>"flash_#{name}", class:'float-right'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title EducApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    = render 'layouts/notification'  
    .container 
      %p
    = yield
    

app/views/users/_user.html.haml
.card.col-lg-3.d-flex.align-items-stretch
  .card-header 
    .fa.fa-user
    = user.email 
    .card-footer 
    Signed Up 
    = time_ago_in_words(user.created_at)
    ago
    .row
    = 'User Sign-In Count'.humanize
    = user.sign_in_count
    .row
    = 'User Current Sign-In'.humanize
    = user.current_sign_in_at 
    .row
    = 'User Last Sign-in'.humanize
    = user.last_sign_in_at
  

app/views/users/index.html.haml
.container
  .form-inline
  = search_form_for @q do |f|
    = f.search_field :email_cont, placeholder: 'email'
    = f.search_field :sign_in_count_eq, placeholder: 'sign in count'
    = f.submit
    .ms-2
    = link_to users_path do
      .fa.fa-sync

  
  %table.table.table-bordered.table-striped.table-success.table-hover
    %thead
      %tr
        %th id
        %th=  sort_link(@q, :email)
        %th=  sort_link(@q, :created_at)
        %th=  sort_link(@q, :sign_in_count)
        %th= 'current_sign_in'.humanize
        %th= 'last_sign_in'.humanize
        %th= 'current_sign_in_ip'.humanize
        %th= 'last_sign_in_ip'.humanize
    %tbody
      - @users.each do |user|
        %tr
          %td= user.id
          %td= user.email
          %td= user.created_at
          %td= user.sign_in_count
          %td= user.current_sign_in_at
          %td= user.last_sign_in_at
          %td= user.current_sign_in_ip
          %td= user.last_sign_in_ip